version: '3.9'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    env_file:
      - app/.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: fastapi_db
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi_secure_user
      POSTGRES_PASSWORD: dj_PG!p_s(99)*74_pR_oP
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/pgsql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fastapi_secure_user -d fastapi" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  postgres_data:
